project:
  type: website

format:
  html:
    theme:
      - cosmo
      - custom.scss
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    title: false
    logo: "logo.svg"
    background: primary
    search: true
  sidebar:
    style: floating
    contents:
      - index.ipynb
      - section: Tutorials
        contents:
          - 07_quickstart_for_web_devs.ipynb        
          - 05_by_example.ipynb
          - tutorials/e2e.ipynb
      - section: Explanations
        contents:
          - 06_explaining_components.ipynb
      - section: API
        contents:
          - 00_core.ipynb
          - 01_components.ipynb
          - 02_xtend.ipynb
          - 03_oauth.ipynb
          - 04_cli.ipynb
      

metadata-files: [nbdev.yml]
